### ISSUE TITLE
Add support for The Things Stack (V3)

### ISSUE THREAD

**Issue by tedenda** [kizniche/ttn-tracker#13]
This application need an update to work with the new version, The Things Stack (V3).

I have started to look in to this today and do not know yet if this is a small thing or more complicated.

**Comment by tedenda** [comment]
I have figured out the new URL and authorisation so the request works fine now with The Things Stack (V3).
But the JSON response is new and I can't figure out what is wrong, I get an exception on the for loop.

**Comment by kizniche** [comment]
Do you have a branch and example output I can look at?

**Comment by tedenda** [comment]
I can push my test branch to GitHub.

I have tried to write response.json to logger.info but that don't work. Do you know how to save the full response to file?

I can use Postman to catch response.json but not sure if that looks exactly the same as if received in code?

**Comment by tedenda** [comment]
I have now created pull request #14 to work with.

**Comment by tedenda** [comment]
Here is the response.json generated with Postman.

[response.txt](https://github.com/kizniche/ttn-tracker/files/6759597/response.txt)

**Comment by sivaelid** [comment]
IS there any update on this issue aas we are all trying to move to V3 . I know there are still issues with the meta data related to the gateway  from TTN which they are aware of  and TTN mapper

**Comment by tedenda** [comment]
No not from my side unfortunately. I have noticed that there have been a issue that will be resolved in v3.14 regarding meta data. The new version will soon be deployed.

**Comment by bockwurst7513** [comment]
I've changed the app.py to work with v3-stack in my repository. Feel free to test it.

**Comment by tedenda** [comment]
Thanks a lot!

I will test it today.
